# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.TextField()),
                ('event_name', models.TextField()),
                ('reader_fqdn', models.TextField()),
                ('reader_id', models.TextField()),
                ('reader_ip', models.TextField()),
                ('door_name', models.TextField(null=True)),
                ('event_level', models.IntegerField()),
                ('event_type', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventlevel',
            fields=[
                ('event_level', models.IntegerField(primary_key=True, serialize=False)),
                ('event_level_name', models.TextField()),
                ('event_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_level', models.IntegerField()),
                ('event_level_name', models.TextField()),
                ('event_name', models.TextField(null=True)),
                ('event_type', models.IntegerField(null=True)),
                ('event_type_description', models.TextField(null=True)),
                ('event_enable', models.BooleanField()),
                ('event_threshold', models.IntegerField(null=True)),
                ('event_threshold_level', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='readermib',
            fields=[
                ('insert_time', models.TextField(null=True)),
                ('reader_fqdn', models.TextField(primary_key=True, serialize=False)),
                ('reader_ip', models.TextField()),
                ('reader_id', models.TextField(null=True)),
                ('reader_role', models.TextField(null=True)),
                ('reader_status', models.TextField(null=True)),
                ('cassandra', models.NullBooleanField()),
                ('postgresql', models.NullBooleanField()),
                ('rfid', models.NullBooleanField()),
                ('finger_vein', models.NullBooleanField()),
                ('door_status', models.NullBooleanField()),
                ('door_open_timer', models.IntegerField(null=True)),
                ('identify_fail', models.IntegerField(null=True)),
                ('account_fail', models.IntegerField(null=True)),
                ('rfid_fail', models.IntegerField(null=True)),
                ('finger_fail', models.IntegerField(null=True)),
                ('competence', models.IntegerField(null=True)),
                ('competence_fail', models.IntegerField(null=True)),
                ('policy_fail', models.IntegerField(null=True)),
                ('apb_fail', models.IntegerField(null=True)),
                ('manager_check_fail', models.IntegerField(null=True)),
                ('os', models.TextField(null=True)),
            ],
        ),
    ]
