# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='door_name',
        ),
    ]
