# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcenter', '0002_remove_event_door_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='door_name',
            field=models.TextField(null=True),
        ),
    ]
